# Generated by Django 3.2.9 on 2022-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
