# Generated by Django 3.2.9 on 2022-02-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
