# Generated by Django 3.2.9 on 2022-01-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_channel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Cohort',
        ),
    ]
