# Generated by Django 3.2.9 on 2022-02-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user',
        ),
    ]
