# Generated by Django 3.2.9 on 2022-01-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220125_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicCohort',
            new_name='Cohort',
        ),
    ]
