# Generated by Django 3.2.9 on 2022-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_publiccohort_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='privateCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_by', models.CharField(max_length=128)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Profile',
                'verbose_name_plural': 'Contact Profiles',
                'ordering': ['timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='Cohort',
            new_name='PublicCohort',
        ),
    ]
