# Generated by Django 3.2.9 on 2022-02-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_user'),
        ('app', '0006_auto_20220202_1137'),
    ]

    operations = [
    ]
