# Generated by Django 3.2.9 on 2022-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220127_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatecohort',
            options={'ordering': ['timestamp'], 'verbose_name': 'private Cohort', 'verbose_name_plural': 'private Cohort'},
        ),
        migrations.AddField(
            model_name='privatecohort',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
