# Generated by Django 3.2.9 on 2022-02-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_rename_user_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='privatecohort',
            name='message',
        ),
        migrations.RemoveField(
            model_name='privatecohort',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='publiccohort',
            name='private',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='session',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='privatecohort',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatecohort',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PublicGroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publiccohort')),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
