# Generated by Django 3.2.9 on 2022-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220203_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
