# Generated by Django 3.2.9 on 2022-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220203_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
