# Generated by Django 3.2.9 on 2022-02-03 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20220203_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
        migrations.AddField(
            model_name='privatecohort',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccohort',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
